### ISSUE TITLE
请问这个下载下来以后要怎么使用？

### ISSUE THREAD

**Issue by saguru23** [TioeAre/orb_slam3_pcl_mapping#1]
请问这个下载下来以后要怎么使用？要把函数复制到原来的orbslam3库里面吗

**Comment by TioeAre** [comment]
> 请问这个下载下来以后要怎么使用？要把函数复制到原来的orbslam3库里面吗

你好，这个的代码只是绘制保存深度相机得到的点云用的，是通过ros节点获取realsense的点云以及orbslam3发布的位姿，然后把得到的点云拼接起来
所以这个repo本身可以单独作为ros的一个节点，不一定必须要嵌入到orbslam3的功能包里面，orbslam3的代码只需要按readme中`orb slam3修改部分`对orbslam3的那几个.cc文件相应的代码改一下就行，让它能够通过ros发布位姿信息
运行时同时启动orbslam3和这个repo来绘制稠密点云

**Comment by saguru23** [comment]
好的谢谢你！看懂作者大大的用意啦！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月9日(星期二) 晚上7:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TioeAre/orb_slam3_pcl_mapping] 请问这个下载下来以后要怎么使用？ (Issue #1)





  
请问这个下载下来以后要怎么使用？要把函数复制到原来的orbslam3库里面吗
  
你好，这个的代码只是绘制保存深度相机得到的点云用的，是通过ros节点获取realsense的点云以及orbslam3发布的位姿，然后把得到的点云拼接起来
 所以这个repo本身可以单独作为ros的一个节点，不一定必须要嵌入到orbslam3的功能包里面，orbslam3的代码只需要按readme中orb slam3修改部分对orbslam3的那几个.cc文件相应的代码改一下就行，让它能够通过ros发布位姿信息
 运行时同时启动orbslam3和这个repo来绘制稠密点云

**Comment by saguru23** [comment]
作者大大您好，请问图上的这几个变量要在哪里进行定义呢？还有变量current_all_KF和current_KF_mnId定义的变量类型是什么😃
![1](https://github.com/TioeAre/orb_slam3_pcl_mapping/assets/139029532/b931934a-3ee4-403f-88e1-e9b9e86c70ab)
自己试着去定义了但是报了很多错

**Comment by TioeAre** [comment]
@saguru23 你好, 我刚才上传了orb slam3部分的, 参见https://github.com/TioeAre/ORB_SLAM3, 时间有点早了, 后续也没有再怎么拓展, 代码也还只是当时很简单的修改了一点点, 你可以看一下那几个commit
![image](https://github.com/TioeAre/orb_slam3_pcl_mapping/assets/89766446/b2581fb6-d663-41d6-aa53-802491959792)
哦对了, opencv跟eigen的库我用的是4.5.5跟3.4.0, 你的版本不一样的话可能要改一下cmakelists.txt换成你的版本

**Comment by saguru23** [comment]
> @saguru23 你好, 我刚才上传了orb slam3部分的, 参见https://github.com/TioeAre/ORB_SLAM3, 时间有点早了, 后续也没有再怎么拓展, 代码也还只是当时很简单的修改了一点点, 你可以看一下那几个commit ![image](https://private-user-images.githubusercontent.com/89766446/296447742-b2581fb6-d663-41d6-aa53-802491959792.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxOTc4NjIsIm5iZiI6MTcwNTE5NzU2MiwicGF0aCI6Ii84OTc2NjQ0Ni8yOTY0NDc3NDItYjI1ODFmYjYtZDY2My00MWQ2LWFhNTMtODAyNDkxOTU5NzkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE0VDAxNTkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkOTRhMDhjODA1NDAwMjU3MDk0NjY0MTYyZDdiZmRmZWQ1OTFiZTU4MWM3NjliMzM5NmRhNWMwMGVhZjZkMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.11Joh20m_l8b89ekBp1pZSb3cEgam0UvNqKyeqH9krU) 哦对了, opencv跟eigen的库我用的是4.5.5跟3.4.0, 你的版本不一样的话可能要改一下cmakelists.txt换成你的版本

感谢作者大大，相应的topic已经发布成功啦😀 一定按着作者大大的代码好好检查自己的问题😀🤝

**Comment by saguru23** [comment]
您好，在运行节点时又遇到了一个问题
想问问作者大大pointcloud_mapping运行时产生段错误的原因会有哪些呢？
有时候会有一两帧成功运行（画面显示绿红黑的大“T”字），然后又段错误终止了







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TioeAre/orb_slam3_pcl_mapping"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月13日(星期六) 晚上7:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TioeAre/orb_slam3_pcl_mapping] 请问这个下载下来以后要怎么使用？ (Issue #1)





 
@saguru23 你好, 我刚才上传了orb slam3部分的, 参见https://github.com/TioeAre/ORB_SLAM3, 时间有点早了, 后续也没有再怎么拓展, 代码也还只是当时很简单的修改了一点点, 你可以看一下那几个commit
 image.png (view on web)
 哦对了, opencv跟eigen的库我用的是4.5.5跟3.4.0, 你的版本不一样的话可能要改一下cmakelists.txt换成你的版本

**Comment by TioeAre** [comment]
@saguru23 抱歉我现在有点记不太清当时都遇到过什么bug了, 印象比较深的只有一个是关于cv_bridge的, 如果你是 通过类似`sudo apt install ros-noetic-desktop-full`的方式安装的话, ros会自动安装4.2.0的opencv和cv_bridge, 如果你的电脑里又自己安装了其他版本的opencv比如我又安装了4.5.5版本时
当用4.5.5的opencv编译之后, 虽然编译时不会报错, 但运行时会因为cv_bridge还是ros自动安装的与4.2.0的opencv配套, 没办法和4.5.5版本的一起正常用, 然后运行时就会出现没有明显错误提示的异常退出

但如果你没有自己安装过别的版本的库的话应该是不会出现我的这个问题的, 你可以同时运行rviz或者rqt_topic来监测各个topic是否有数据, 有数据的话可以给pointcloud_mapping打几个断点看看是那里退出的

**Comment by saguru23** [comment]
好的我试着找找我的问题出在哪里，找到原因的话第一时间告诉您！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月14日(星期天) 中午12:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TioeAre/orb_slam3_pcl_mapping] 请问这个下载下来以后要怎么使用？ (Issue #1)





 
@saguru23 抱歉我现在有点记不太清当时都遇到过什么bug了, 印象比较深的只有一个是关于cv_bridge的, 如果你是 通过类似sudo apt install ros-noetic-desktop-full的方式安装的话, ros会自动安装4.2.0的opencv和cv_bridge, 如果你的电脑里又自己安装了其他版本的opencv比如我又安装了4.5.5版本时
 当用4.5.5的opencv编译之后, 虽然编译时不会报错, 但运行时会因为cv_bridge还是ros自动安装的与4.2.0的opencv配套, 没办法和4.5.5版本的一起正常用, 然后运行时就会出现没有明显错误提示的异常退出
 
但如果你没有自己安装过别的版本的库的话应该是不会出现我的这个问题的, 你可以同时运行rviz或者rqt_topic来监测各个topic是否有数据, 有数据的话可以给pointcloud_mapping打几个断点看看是那里退出的

**Comment by saguru23** [comment]
我按照ubuntu20的默认版本配了一遍，问题解决了。按照ubuntu的默认版本不容易出现cv_bridge错连4.2.0等等问题

**Comment by saguru23** [comment]
> 我按照ubuntu20的默认版本配了一遍，问题解决了。按照ubuntu的默认版本不容易出现cv_bridge错连4.2.0等等问题

我用的是cv4.2，pcl1.10，vtk8.2，pangolin0.8->ubuntu20
