### ISSUE TITLE
稠密建图部分该如何执行呢？

### ISSUE THREAD

**Issue by Axeliar** [TioeAre/orb_slam3_pcl_mapping#2]
将其放在了catkin_ws/src目录下，与orb-slam3同级，编译后不知该如何运行？

**Comment by TioeAre** [comment]
> 将其放在了catkin_ws/src目录下，与orb-slam3同级，编译后不知该如何运行？

可以参照一下这个issue，我之前对orbslam3也稍微改了一些地方发布位姿，用原本ros启动orbslam3之后再单独rosrun这个仓库编译出的pointcloud_mapping应该就可以了
https://github.com/TioeAre/orb_slam3_pcl_mapping/issues/1#issuecomment-1890426462
