### ISSUE TITLE
是否可以在Ubuntu18.04 ros-melodic下编译使用呢？

### ISSUE THREAD

**Issue by Axeliar** [TioeAre/orb_slam3_pcl_mapping#3]
我在Ubuntu18.04下成功cmake生成了/build/devel/lib/pointcloud_mapping/pointcloud_mapping，但无法执行`rosrun pointcloud_mapping pointcloud_mapping`指令。
报错信息：
[rosrun] Couldn't find executable name pointcloud_mapping
[rosrun] Found the following, but they're either not files, or not executable.

请问在ros-melodic下编译是否需要进行什么额外的修改吗？

**Comment by TioeAre** [comment]
> 我在Ubuntu18.04下成功cmake生成了/build/devel/lib/pointcloud_mapping/pointcloud_mapping，但无法执行`rosrun pointcloud_mapping pointcloud_mapping`指令。
> 报错信息：
> [rosrun] Couldn't find executable name pointcloud_mapping
> [rosrun] Found the following, but they're either not files, or not executable.
> 
> 请问在ros-melodic下编译是否需要进行什么额外的修改吗？

应该是不用别的修改的，既然可以编译成功，是不是没有source devel/setup.bash呀，或者你直接在命令行运行./build/devel/lib/pointcloud_mapping/pointcloud_mapping试试

**Comment by Axeliar** [comment]
> 应该是不用别的修改的，既然可以编译成功，是不是没有source devel/setup.bash呀，或者你直接在命令行运行./build/devel/lib/pointcloud_mapping/pointcloud_mapping试试

我尝试了source但仍然不行，实际上我输入`rosrun`后第一次tab是可以找到`pointcloud_mapping`的，但是在`rosrun pointcloud_mapping`的情况下再次tab就无法进行补全也找不到可执行文件了。
直接运行/build/devel/lib/pointcloud_mapping/pointcloud_mapping后会显示 `段错误（核心已转储）`。

**Comment by TioeAre** [comment]
> 我在Ubuntu18.04下成功cmake生成了/build/devel/lib/pointcloud_mapping/pointcloud_mapping，但无法执行`rosrun pointcloud_mapping pointcloud_mapping`指令。
> 报错信息：
> [rosrun] Couldn't find executable name pointcloud_mapping
> [rosrun] Found the following, but they're either not files, or not executable.
> 
> 请问在ros-melodic下编译是否需要进行什么额外的修改吗？

等会，你是cmake然后make编译的吗，还是catkin make

**Comment by Axeliar** [comment]
> 等会，你是cmake然后make编译的吗，还是catkin make

是的
`mkdir build
cd build
cmake ..
make`

**Comment by Axeliar** [comment]
> 等会，你是cmake然后make编译的吗，还是catkin make

是的
`mkdir build`
`cd build`
`cmake ..`
`make`

**Comment by TioeAre** [comment]
> > 等会，你是cmake然后make编译的吗，还是catkin make
> 
> 是的
> `mkdir build`
> `cd build`
> `cmake ..`
> `make`

直接catkin_make就可以
